2022-10-14 13:54:02,275 DEBUG    root            Loaded Command Group: ['gcloud', 'config']
2022-10-14 13:54:02,276 DEBUG    root            Loaded Command Group: ['gcloud', 'config', 'configurations']
2022-10-14 13:54:02,278 DEBUG    root            Loaded Command Group: ['gcloud', 'config', 'configurations', 'activate']
2022-10-14 13:54:02,280 DEBUG    root            Running [gcloud.config.configurations.activate] with arguments: [CONFIGURATION_NAME: "hob"]
2022-10-14 13:54:02,281 DEBUG    root            (gcloud.config.configurations.activate) Cannot activate configuration [hob], it does not exist.
Traceback (most recent call last):
  File "/Users/ledemn/Desktop/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/ledemn/Desktop/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/Users/ledemn/Desktop/google-cloud-sdk/lib/surface/config/configurations/activate.py", line 58, in Run
    named_configs.ConfigurationStore.ActivateConfig(args.configuration_name)
  File "/Users/ledemn/Desktop/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 309, in ActivateConfig
    .format(config_name))
googlecloudsdk.core.configurations.named_configs.NamedConfigError: Cannot activate configuration [hob], it does not exist.
2022-10-14 13:54:02,282 ERROR    root            (gcloud.config.configurations.activate) Cannot activate configuration [hob], it does not exist.
2022-10-14 13:54:02,295 DEBUG    root            Metrics reporting process started...
